---
# This is an empty istio control plane, used to force creation of p4sa
apiVersion: install.istio.io/v1alpha2
kind: IstioOperator
metadata:
  annotations:
    gke.io/cluster: "gke://[PROJECT_ID]/us-central1-c/asm-free-trial" # {"$ref":"#/definitions/io.k8s.cli.substitutions.gkeio-cluster"}
spec:
  profile: minimal
  trafficManagement:
    enabled: false
  policy:
    enabled: false
  telemetry:
    enabled: false
  security:
    enabled: false
  configManagement:
    enabled: false
  gateways:
    enabled: false
  autoInjection:
    enabled: false
  coreDNS:
    enabled: false
