---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: asm-galley-iam-policy
  namespace: "[PROJECT_ID]"  # {"$ref":"#/definitions/io.k8s.cli.setters.gcloud.core.project"}
  annotations:
    gke.io/cluster: "bootstrap://" # {"$ref":"#/definitions/io.k8s.cli.substitutions.bootstrap-cluster"}
spec:
  member: serviceAccount:[PROJECT_ID].svc.id.goog[istio-system/asm-galley-service-account] # {"$ref":"#/definitions/io.k8s.cli.substitutions.galley-service-account"}
  role: roles/meshconfig.writer 
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: PROJECT_ID # {"$ref":"#/definitions/io.k8s.cli.substitutions.iam-policy-member-project"}
