apiVersion: identity.cnrm.cloud.google.com/v1alpha2
kind: IdentityNamespace
metadata:
  name: default
  namespace: "[PROJECT_ID]" # {"$ref":"#/definitions/io.k8s.cli.substitutions.gcloud.core.project"}
spec: {}
---
apiVersion: container.cnrm.cloud.google.com/v1alpha2
kind: ContainerCluster
metadata:
  clusterName: "[PROJECT_ID]/us-central1-c/asm-free-trial" # {"$ref":"#/definitions/io.k8s.cli.substitutions.full-cluster-name"}
  name: asm-free-trial # {"$ref":"#/definitions/io.k8s.cli.setters.cluster-name"}
  namespace: "[PROJECT_ID]" # {"$ref":"#/definitions/io.k8s.cli.substitutions.gcloud.core.project"}
spec:
  location: us-central1-c # {"$ref":"#/definitions/io.k8s.cli.setters.location"}
  workloadIdentity:
    identityNamespace: default
  labels:
    mesh_id: "proj-[PROJECT_ID]" # {"$ref":"#/definitions/io.k8s.cli.substitutions.mesh-id"}
  loggingService: logging.googleapis.com/kubernetes
  monitoringService: monitoring.googleapis.com/kubernetes
  ipAllocationPolicy:
    useIpAliases: true
  addonsConfig:
    horizontalPodAutoscaling:
      disabled: false
    httpLoadBalancing:
      disabled: true
    cloudrunConfig:
      disabled: true # {"$ref:","#/definitions/io.k8s.cli.setters.cloudrun-config-disabled"}
  masterAuth:
    username: admin
  network: default
  networkPolicy:
    enabled: true
  minMasterVersion: "1.15.11-gke.1"
  nodeConfig:
    metadata:
      disable-legacy-endpoints: "true"
---
apiVersion: container.cnrm.cloud.google.com/v1alpha2
kind: ContainerNodePool
metadata:
  clusterName: "[PROJECT_ID]/us-central1-c/asm-free-trial" # {"$ref":"#/definitions/io.k8s.cli.substitutions.full-cluster-name"}
  name: default-pool
  namespace: "[PROJECT_ID]" # {"$ref":"#/definitions/io.k8s.cli.substitutions.gcloud.core.project"}
spec:
  initialNodeCount: 2
  autoscaling:
    minNodeCount: 4 # {"$ref":"#/definitions/io.k8s.cli.setters.minNodeCount"}
    maxNodeCount: 8 # {"$ref":"#/definitions/io.k8s.cli.setters.maxNodeCount"}
  nodeConfig:
    diskSizeGb: 100
    diskType: pd-standard
    machineType: n1-standard-4
    preemptible: false
    oauthScopes:
    - "https://www.googleapis.com/auth/cloud-platform"
    - "https://www.googleapis.com/auth/compute"
    - "https://www.googleapis.com/auth/devstorage.read_only"
    - "https://www.googleapis.com/auth/logging.write"
    - "https://www.googleapis.com/auth/monitoring"
    - "https://www.googleapis.com/auth/service.management.readonly"
    - "https://www.googleapis.com/auth/servicecontrol"
    - "https://www.googleapis.com/auth/trace.append"
    metadata:
      disable-legacy-endpoints: "true"
  management:
    autoRepair: true
    autoUpgrade: true
  clusterRef:
    name: asm-free-trial # {"$ref":"#/definitions/io.k8s.cli.setters.cluster-name"}

