apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    gke.io/cluster: "gke://[PROJECT_ID]/us-central1-c/asm-free-trial" # {"$ref":"#/definitions/io.k8s.cli.substitutions.gkeio-cluster"}
  name: istio-mesh-td
  namespace: istio-system
  labels:
    release: istiod
data:

  mesh: |
    # See https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#MeshConfig

    # Disable envoy tracing
    enableTracing:                     false

    # Envoy access log settings.
    # Set accessLogFile to empty string to disable access log.
    accessLogFile:                     "/dev/stdout"
    accessLogEncoding:                 TEXT
    accessLogFormat: ""
    enableEnvoyAccessLogService: false

    # Connection timeout for Envoy.
    connectTimeout:                    1s

    # Export services/virtual services/destination rules to all namespaces.
    defaultServiceExportTo:            ["*"]
    defaultVirtualServiceExportTo:     ["*"]
    defaultDestinationRuleExportTo:    ["*"]

    # Disable Mixer functionality. Assume Mixerv2 or telemetry lite will be used by default.
    mixerCheckServer: ""
    mixerReportServer: ""
    disablePolicyChecks: true
    policyCheckFailOpen:               false
    sidecarToTelemetrySessionAffinity: false

    # Upgrade to http2 if possible (https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#MeshConfig-H2UpgradePolicy)
    h2UpgradePolicy: UPGRADE

    # Kubernetes namespace where cluster-side components are installed
    rootNamespace:                     "istio-system"

    # If set then set SO_KEEPALIVE on the socket to enable TCP Keepalives.
    tcpKeepalive:
      probes: 9
      time: 7200s
      interval: 75s
      
    # Port on which Envoy should listen for incoming connections from other services.
    proxyListenPort:                   15001

    # This is the k8s ingress service name, update if you used a different name
    ingressService:                    "asm-td-ingressgateway"
    ingressControllerMode: DEFAULT
    ingressClass: "istio"

    # Enable all outbound pod traffic by default
    outboundTrafficPolicy:
      mode: ALLOW_ANY

    dnsRefreshRate:                    5s
    protocolDetectionTimeout:          100ms

    enableAutoMtls: true

    # Extra
    authPolicy: NONE

    # Port on which Envoy should listen for HTTP PROXY requests if set.
    proxyHttpPort: 15080

    defaultConfig:
      configPath: /etc/istio/proxy

      binaryPath: /usr/local/bin/envoy

      serviceCluster: istio-proxy

      drainDuration: 45s

      parentShutdownDuration: 60s

      controlPlaneAuthPolicy: NONE

      connectTimeout: 1s

      statsdUdpAddress: ""

      envoyMetricsService: {}

      envoyAccessLogService: {}

      proxyAdminPort: 15000

      interceptionMode: REDIRECT

      concurrency: 0

      statNameLength: 189
